### ISSUE TITLE
VR does not reconnect when mongo goes away

### ISSUE THREAD

**Issue by bb-migration** [yougov/velociraptor#144]
Originally reported by: **Brent Tubbs (Bitbucket: [btubbs](http://bitbucket.org/btubbs), GitHub: [btubbs](http://github.com/btubbs))**

---

Lorenzo Bolla created this ticket on our internal system.  I'm moving it to live with the rest of the tickets.

If mongo goes away, pymongo raises AutoReconnect, but VR does not seem to handle it properly and reconnect, so a restart is needed.

```
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0 [2015-02-27 04:11:06,849: ERROR/MainProcess] Task vr.server.tasks.build_app[3518821a-87e5-4bd7-b70f-5beb490dfa9f] raised exception: AutoReconnect('[Errno 104] Connection reset by peer',)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0 Traceback (most recent call last):
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/celery/task/trace.py", line 233, in trace_task
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     R = retval = fun(*args, **kwargs)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/celery/task/trace.py", line 420, in __protected_call__
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     return self.run(*args, **kwargs)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/tasks.py", line 68, in wrapper
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     func(*args, **kwargs)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/tasks.py", line 177, in build_app
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     _do_build(build, build_yaml)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/tasks.py", line 270, in _do_build
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     build.file.save(filepath, File(localfile))
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/models/fields/files.py", line 86, in save
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     self.name = self.storage.save(name, content)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/django/core/files/storage.py", line 45, in save
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     name = self._save(name, content)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/storages.py", line 43, in _save
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     self.fs.put(content, filename=name)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/gridfs/__init__.py", line 140, in put
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     grid_file.write(data)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/gridfs/grid_file.py", line 343, in write
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     self.__flush_data(to_write)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/gridfs/grid_file.py", line 222, in __flush_data
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     self._ensure_index()
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/gridfs/grid_file.py", line 172, in _ensure_index
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     unique=True)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/collection.py", line 1167, in ensure_index
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     return self.create_index(key_or_list, cache_for, **kwargs)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/collection.py", line 1060, in create_index
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     indexes=[index])
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/database.py", line 445, in command
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     uuid_subtype, compile_re, **kwargs)[0]
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/database.py", line 345, in _command
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     for doc in cursor:
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/cursor.py", line 1058, in next
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     if len(self.__data) or self._refresh():
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/cursor.py", line 1002, in _refresh
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     self.__uuid_subtype))
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/cursor.py", line 915, in __send_message
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     res = client._send_message_with_response(message, **kwargs)
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0   File "/app/.heroku/venv/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1210, in _send_message_with_response
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0     raise AutoReconnect(str(e))
Feb 27 04:11:06 vybuild4 supervisord: velociraptor-v138-vr2-c79f5fe6-worker-0 None: [Errno 104] Connection reset by peer
```

---
- Bitbucket: https://bitbucket.org/yougov/velociraptor/issue/144

**Comment by jaraco** [comment]
I'm declaring this issue solved. I'm not aware of any ongoing issues with MongoDB connection reliability.
