### ISSUE TITLE
HTTP500 while creating a swarm with a name that already exists.

### ISSUE THREAD

**Issue by amateja** [yougov/velociraptor#207]
Howdy!

I've recently noticed that I get HTTP500 error while creating a brand new swarm by coincidence with name that already exists. It is due to `ProgrammingError: autocommit cannot be used inside a transaction` exception raised while saving swarm object. @lbolla knows details 😄.

Cheers
Andrzej

**Comment by lbolla** [comment]
Here is a complete stacktrace of the error.

> ERROR:django.request:Internal Server Error: /swarm/
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/venv/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/.heroku/venv/lib/python2.7/site-packages/reversion/revisions.py", line 323, in do_revision_context
    return func(*args, **kwargs)
  File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/views.py", line 306, in edit_swarm
    swarm.save()
  File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/models.py", line 629, in save
    super(Swarm, self).save()
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/transaction.py", line 271, in __exit__
    connection.set_autocommit(True)
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 295, in set_autocommit
    self._set_autocommit(autocommit)
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 218, in _set_autocommit
    self.connection.autocommit = autocommit
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 218, in _set_autocommit
    self.connection.autocommit = autocommit
  File "/app/.heroku/venv/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/common/object_wrapper.py", line 97, in __setattr__
    _ObjectProxy.__setattr__(self, name, value)
ProgrammingError: autocommit cannot be used inside a transaction

**Comment by lbolla** [comment]
Fixed in https://github.com/yougov/vr.server/commit/f7578659c000e15aeba348affe71ecedbdc200e4
