### ISSUE TITLE
Duplicate VR users are created

### ISSUE THREAD

**Issue by lbolla** [yougov/velociraptor#218]
I am intermittently seeing a 500 error when visiting VR. Newrelic shows:
 
`django.contrib.auth.models:MultipleObjectsReturned: get() returned more than one User -- it returned 2!`
 
This occured most recently when visiting VR in a tab open from the previous day, receiving a 'session expired' alert, and logging in with my user/pass.
 
It appears that I have two VR users, 'matthew.barry' and 'Matthew.Barry'. The duplicate (lowercase version) was deleted a few weeks ago but it seems to have reappeared. allanc deleted the lowercase version and renamed the capitalized version to be lowercase in line with the VR users naming convention.
 
I am not sure what the root cause of the duplicate creation is.

**Comment by lbolla** [comment]
Traceback from a recent failure:
```
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
  File "/app/.heroku/venv/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 155, in handle
  File "/app/.heroku/venv/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
  File "/app/.heroku/venv/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
  File "/app/.heroku/venv/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
  File "/app/.heroku/venv/lib/python2.7/site-packages/newrelic/api/web_transaction.py", line 1286, in _nr_wsgi_application_wrapper_
  File "/app/.heroku/venv/lib/python2.7/site-packages/newrelic/api/web_transaction.py", line 813, in __init__
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
  File "/app/.heroku/venv/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 423, in _nr_wrapper_BaseHandler_get_response_
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
  File "/app/.heroku/venv/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 220, in wrapper
  File "/app/.heroku/venv/lib/python2.7/site-packages/baton_django/__init__.py", line 100, in process_request
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
  File "/app/.heroku/venv/lib/python2.7/site-packages/baton_django/__init__.py", line 156, in authenticate
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/models/query.py", line 405, in get_or_create
  File "/app/.heroku/venv/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
django.contrib.auth.models:MultipleObjectsReturned: get() returned more than one User -- it returned 2!
```
