### ISSUE TITLE
Swarming app after changing stack results in error build has no file

### ISSUE THREAD

**Issue by jaraco** [yougov/velociraptor#220]
After updating the pmxbot app from trusty to xenial stack and dispatching the swarm at the same version, I see this in the events:

![image](https://user-images.githubusercontent.com/308610/33960418-b0838b22-e018-11e7-9ba3-13625503f61a.png)

Clicking on one of those failed pushes shows:

```
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/tasks.py", line 91, in wrapper
    func(*args, **kwargs)
  File "/app/.heroku/venv/lib/python2.7/site-packages/vr/server/tasks.py", line 178, in deploy
    assert release.build.file, "Build %s has no file" % release.build
AssertionError: Build pmxbot-19.8 has no file
```

**Comment by jaraco** [comment]
And as you can see, swarming again, a new build is created.

**Comment by pawciobiel** [comment]
The same exception occurred when me and Bryan were swarming the same tag to two different pools in the same time.
