### ISSUE TITLE
TypeError during uptest invocation

### ISSUE THREAD

**Issue by adblair** [yougov/velociraptor#224]
It seems hashlib is being given unicode instead of bytes here, when running in Python 3.5:
```
Traceback (most recent call last):
  File "/usr/local/bin/vrun", line 11, in <module>
    sys.exit(ImageRunner.invoke())
  File "/usr/local/lib/python3.5/site-packages/vr/runners/base.py", line 361, in invoke
    cls().main()
  File "/usr/local/lib/python3.5/site-packages/vr/runners/base.py", line 72, in main
    cmd()
  File "/usr/local/lib/python3.5/site-packages/vr/runners/base.py", line 294, in uptest
    self._lxc_start(special_cmd=cmd)
  File "/usr/local/lib/python3.5/site-packages/vr/runners/base.py", line 204, in _lxc_start
    args = self.get_lxc_args(special_cmd=special_cmd)
  File "/usr/local/lib/python3.5/site-packages/vr/runners/base.py", line 221, in get_lxc_args
    name += \'-TMP\' + hashlib.md5(special_cmd).hexdigest()[:8]
    TypeError: Unicode-objects must be encoded before hashing
```

**Comment by jaraco** [comment]
So glad to Python 3 being adopted. Let's get this fixed ASAP.

**Comment by jaraco** [comment]
Looking at [the code](https://github.com/yougov/vr.runners/blob/2dffba99d1219d7ec727d6782689cb0fab98aceb/vr/runners/base.py#L210-L223), I'm wondering if it makes sense at all to hash that value. After all, the 'special_cmd' is only ever 'shell' or 'uptest', which always hash to the same value. Why mask the purpose of the container?

Aah, because 'special_cmd' isn't the indicator "shell" or "uptests", but is the path inside the container that's going to be run... which may contain path separators such as `/`.

**Comment by jaraco** [comment]
Released as vr.runners 3.0.1.
