### ISSUE TITLE
TypeError in sseclient

### ISSUE THREAD

**Issue by jaraco** [yougov/velociraptor#228]
As reported in https://github.com/btubbs/sseclient/issues/13, a TypeError occurs when deploying the vr.server web proc on Python 3.

```
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/app/.heroku/venv/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/app/.heroku/venv/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request
    for item in respiter:
  File "/app/.heroku/venv/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 646, in __iter__
    for item in self.generator:
  File "/app/.heroku/venv/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 1053, in __iter__
    for data in self.iterable:
  File "/app/.heroku/venv/lib/python3.6/site-packages/vr/server/events.py", line 51, in __iter__
    yield self.next()
  File "/app/.heroku/venv/lib/python3.6/site-packages/vr/server/events.py", line 61, in next
    return ev.dump()
  File "/app/.heroku/venv/lib/python3.6/site-packages/sseclient.py", line 116, in dump
    lines.extend('data: %s' % d for d in self.data.split('\n'))
TypeError: a bytes-like object is required, not 'str'
```

The sseclient expects the `data` value to be unicode (or at least `str`).

It's not clear to me if the publisher should be sending unicode, or if the ProcListener should be decoding bytes.

**Comment by jaraco** [comment]
A simple test of a redis pubsub indicates to me that even if you publish text to a pubsub, it comes back as bytes:

```
sseclient master $ rwt redis
Collecting redis
  Using cached https://files.pythonhosted.org/packages/3b/f6/7a76333cf0b9251ecf49efff635015171843d9b977e4ffcf59f9c4428052/redis-2.10.6-py2.py3-none-any.whl
Installing collected packages: redis
Successfully installed redis-2.10.6
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> db = redis.StrictRedis()
>>> db
StrictRedis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>
>>> ps = db.pubsub()
>>> ps.subscribe(['foo'])
>>> db.publish('foo', 'bar')
1
>>> next(ps.listen())
{'type': 'subscribe', 'pattern': None, 'channel': b'foo', 'data': 1}
>>> next(ps.listen())
{'type': 'message', 'pattern': None, 'channel': b'foo', 'data': b'bar'}
```

Therefore, it must be the responsibility of vr.server.events to decode these bytes.
